version: "3.9"

services:
  postgresdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  agorabackend:
    image: agoraback
    depends_on:
      - postgresdb
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - backendnet

volumes:
  pgdata:

networks:
  backendnet: