services:
  postgresdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  agorabackend:
    image: agoraback
    depends_on:
      - postgresdb
    environment:
      - DATABASE_URL=postgres://user:pass@address:port/dbname
      - JWT_SECRET=dsada12123dsdas12123
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - backendnet

volumes:
  pgdata:

networks:
  backendnet: